const http = require('http');
const { Server } = require("socket.io");

const PORT = process.env.PORT || 5000;
const server = http.createServer((req, res) => {
    res.writeHead(200);
    res.end('DeskLink Signaling Server');
});

const io = new Server(server, {
    cors: {
        origin: "*",
        methods: ["GET", "POST"]
    }
});

io.on("connection", (socket) => {
    console.log("New connection:", socket.id);

    // Identify: User registers their ID (could be random ID generated by client)
    socket.on("register", (myId) => {
        console.log(`Socket ${socket.id} registered as ${myId}`);
        socket.join(myId); // Join a room with their own ID for easy addressing
    });

    // Call User: Caller sends this to signal intent to connect
    socket.on("call-user", ({ userToCall, signalData, from }) => {
        console.log(`Call from ${from} to ${userToCall}`);
        io.to(userToCall).emit("call-user", { signal: signalData, from });
    });

    // Answer Call: Callee sends this back
    socket.on("answer-call", ({ to, signal }) => {
        console.log(`Answer from ${socket.id} to ${to}`);
        io.to(to).emit("call-accepted", { signal });
    });

    // Ice Candidate exchange
    socket.on("ice-candidate", ({ to, candidate }) => {
        console.log(`ICE candidate from ${socket.id} to ${to}`);
        io.to(to).emit("ice-candidate", { candidate, from: socket.id });
    });

    socket.on("disconnect", () => {
        console.log("Disconnected:", socket.id);
    });
});

server.listen(PORT, () => {
    console.log(`Signaling server listening on port ${PORT}`);
});
